name: phishing-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - fastapi
  - uvicorn
  - loguru
  - numpy
  - pydantic
  - typing
  - scikit-learn
  - pip
  - pip:
    - docker
    - axios

